// Code generated by jzero. DO NOT EDIT.
package types

import (
	"time"
)

var (
	_ = time.Now()
)

type GetVersionRequest struct {
}

type GetVersionResponse struct {
	Version   string `json:"version"`
	GoVersion string `json:"goVersion"`
	Commit    string `json:"commit"`
	Date      string `json:"date"`
}

type PumpBotRequest struct {
	Switch string `form:"switch,optional,default=on"`
}

type PumpBotResponse struct {
	Message string `json:"message"`
}
