// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: v1/fee.proto

package feepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Server_GetHealth_FullMethodName               = "/feepb.Server/GetHealth"
	Server_GetTransactionFee_FullMethodName       = "/feepb.Server/GetTransactionFee"
	Server_GetTransactionFeeStream_FullMethodName = "/feepb.Server/GetTransactionFeeStream"
)

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerClient interface {
	GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	GetTransactionFee(ctx context.Context, in *TransactionFee, opts ...grpc.CallOption) (*TransactionFeeResponse, error)
	GetTransactionFeeStream(ctx context.Context, in *TransactionFee, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransactionFeeStreamResponse], error)
}

type serverClient struct {
	cc grpc.ClientConnInterface
}

func NewServerClient(cc grpc.ClientConnInterface) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Server_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) GetTransactionFee(ctx context.Context, in *TransactionFee, opts ...grpc.CallOption) (*TransactionFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionFeeResponse)
	err := c.cc.Invoke(ctx, Server_GetTransactionFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) GetTransactionFeeStream(ctx context.Context, in *TransactionFee, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransactionFeeStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Server_ServiceDesc.Streams[0], Server_GetTransactionFeeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransactionFee, TransactionFeeStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Server_GetTransactionFeeStreamClient = grpc.ServerStreamingClient[TransactionFeeStreamResponse]

// ServerServer is the server API for Server service.
// All implementations must embed UnimplementedServerServer
// for forward compatibility.
type ServerServer interface {
	GetHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	GetTransactionFee(context.Context, *TransactionFee) (*TransactionFeeResponse, error)
	GetTransactionFeeStream(*TransactionFee, grpc.ServerStreamingServer[TransactionFeeStreamResponse]) error
	mustEmbedUnimplementedServerServer()
}

// UnimplementedServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerServer struct{}

func (UnimplementedServerServer) GetHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedServerServer) GetTransactionFee(context.Context, *TransactionFee) (*TransactionFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionFee not implemented")
}
func (UnimplementedServerServer) GetTransactionFeeStream(*TransactionFee, grpc.ServerStreamingServer[TransactionFeeStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetTransactionFeeStream not implemented")
}
func (UnimplementedServerServer) mustEmbedUnimplementedServerServer() {}
func (UnimplementedServerServer) testEmbeddedByValue()                {}

// UnsafeServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerServer will
// result in compilation errors.
type UnsafeServerServer interface {
	mustEmbedUnimplementedServerServer()
}

func RegisterServerServer(s grpc.ServiceRegistrar, srv ServerServer) {
	// If the following call pancis, it indicates UnimplementedServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Server_ServiceDesc, srv)
}

func _Server_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).GetHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_GetTransactionFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionFee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).GetTransactionFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_GetTransactionFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).GetTransactionFee(ctx, req.(*TransactionFee))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_GetTransactionFeeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransactionFee)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerServer).GetTransactionFeeStream(m, &grpc.GenericServerStream[TransactionFee, TransactionFeeStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Server_GetTransactionFeeStreamServer = grpc.ServerStreamingServer[TransactionFeeStreamResponse]

// Server_ServiceDesc is the grpc.ServiceDesc for Server service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Server_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feepb.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _Server_GetHealth_Handler,
		},
		{
			MethodName: "GetTransactionFee",
			Handler:    _Server_GetTransactionFee_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTransactionFeeStream",
			Handler:       _Server_GetTransactionFeeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/fee.proto",
}
